### ISSUE TITLE
help with project

### ISSUE THREAD

**Issue by razataiab** [JacobEckroth/BetterChess#8]

**Comment by JacobEckroth** [comment]
Hey I'm not maintaining this anymore so I'll just add you as a contributor. Feel free to respond to any other issues / add anyone else as well.

**Comment by JacobEckroth** [comment]
Added you as a collaborator. Go crazy with it!

**Comment by razataiab** [comment]
Hey, I am a student and developing a similar chess application using C++
and SDL. If you could help me with it, I would really appreciate it.

**Comment by JacobEckroth** [comment]
No promises, but feel free to shoot me a message on linked in (Jacob Eckroth)

I haven't worked in C++ in a while haha
